version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simple_shop
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_USER: vahan
      PGADMIN_DEFAULT_EMAIL: vahan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 5050:80
